CREATE DATABASE IF NOT EXISTS ekobelth
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

CREATE USER IF NOT EXISTS 'ekobelth'@'localhost' IDENTIFIED BY 'troque-esta-senha';
GRANT ALL PRIVILEGES ON ekobelth.* TO 'ekobelth'@'localhost';
FLUSH PRIVILEGES;

USE ekobelth;

CREATE TABLE IF NOT EXISTS tratamentos (
  id INT AUTO_INCREMENT PRIMARY KEY,
  paciente VARCHAR(255) NOT NULL,
  medicamento VARCHAR(255) NOT NULL,
  via VARCHAR(100) NOT NULL DEFAULT '',
  dose VARCHAR(100) NOT NULL DEFAULT '',
  frequencia VARCHAR(100) NOT NULL DEFAULT '',
  estoque VARCHAR(50) NOT NULL DEFAULT '',
  inicio VARCHAR(20) NOT NULL DEFAULT '',
  fim VARCHAR(20) NOT NULL DEFAULT '',
  obs TEXT NOT NULL,
  criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
